@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.alcatrazescapee.mcjunitlib;

import javax.annotation.ParametersAreNonnullByDefault;

import mcp.MethodsReturnNonnullByDefault;